### ISSUE TITLE
Automation for AWS_ELASTICLOADBALANCING_ENI_LIMIT_REACHED

### ISSUE THREAD

**Issue by mwpatrick** [aws/aws-health-tools#12]
On receipt of the out of ENIs event
- pulls the region from the event
- pulls the ENIs from that region
- deletes unattached ENIs.

**Comment by mwpatrick** [comment]
Working on the code. Good so far - testing with a test event (below) finds available ENIs and removes them.
Code is leaving an in-use ENI alone.

{
  "region": "us-east-2",
  "detail": {"eventTypeCode": "ENI Exhaust"}
}

**Comment by mwpatrick** [comment]
Expect to be done with this soon - need to do some final testing, including with the CloudFormation template

**Comment by tipuq** [comment]
Closed as PR was merged: https://github.com/aws/aws-health-tools/pull/22
