### ISSUE TITLE
Automation for AWS_ELASTICLOADBALANCING_INSUFFICIENT_IPS_IN_SUBNET

### ISSUE THREAD

**Issue by mwpatrick** [aws/aws-health-tools#13]
On receipt of the out of IPs event
- pulls the ELBs from the event, 
- For each ELB
-- Get subnets from ELB
-- unattached ENIs in those subnets
-- Remove unattached ENI

Possible improvement might be a single API call to get all the unattached ENIs 
in the region of the ELBs first instead of an ENI API call per ELB.

**Comment by mwpatrick** [comment]
Code needs testing with ELB events via Personal Health service. Likely changes still needed in distinguishing Classic vs Application load balancer in the events.

**Comment by mwpatrick** [comment]
Updating my branch a bit but running into CloudFormation 4KB limitation on script source. Either need to wait until ELB releases a way to tell CLB and ALB apart in the event or going to have to add even more code to deal with "not found" responses when querying the API since right now we have to run each supplied ELB name through BOTH APIs.

Maybe this can get around the 4KB limitation by switching to multiple functions orchestrated by StepFunctions. The other option is going to be packaging up the code in a ZIP in an S3 bucket and having CFN reference that but that requires keeping that ZIP up to date along with everything else.

https://github.com/mwpatrick/aws-health-tools/tree/NotENoughIPs

**Comment by tipuq** [comment]
THis was completed.
