### ISSUE TITLE
error when testing Lambda function 

### ISSUE THREAD

**Issue by jaydo1** [aws/aws-health-tools#24]
Hi 

I used the CF template to create a new SNS-topic-publisher the stack completes successfully but when I try to test the lambda function I keep getting 
{
  "errorMessage": "RequestId: e77000d8-0d19-11e7-94ee-0bca4af62b78 Process exited before completing request"
}

not sure what is happening any assistance would be greatly appreciated

**Comment by premsurya** [comment]
May I know what type of what was your test setup ? Did you try to just test the lambda function by clicking the "Test" button in the Lambda module? If so, what is the test event you used ? Did you change it from the default? 

For reference, pasting below a sample test event which you could use ( In the Lambda screen Click Actions > Configure Test Event and then remove the default test event and add the below and click "Save and Test" )

{
  "version": "0",
  "id": "7bf73129-1428-4cd3-a780-95db273d1602",
  "detail-type": "AWS Health Event",
  "source": "aws.health",
  "account": "123456789012",
  "time": "2016-06-05T06:27:57Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "eventArn": "arn:aws:health:ap-southeast-2::event/AWS_ELASTICLOADBALANCING_API_ISSUE_90353408594353980",
    "service": "ELASTICLOADBALANCING",
    "eventTypeCode": "AWS_ELASTICLOADBALANCING_API_ISSUE",
    "eventTypeCategory": "issue",
    "startTime": "Sat, 04 Jun 2016 05:01:10 GMT",
    "endTime": "Sat, 04 Jun 2016 05:30:57 GMT",
    "eventDescription": [
      {
        "language": "en_US",
        "latestDescription": "A description of the event will be provided here"
      }
    ]
  }
}

**Comment by jaydo1** [comment]
Thanks for getting back to me 

I have tried that test and updated the region and arn for my SNS topic but I get now get a different error 

2017-03-20T21:11:37.819Z	ce24f3a8-0db1-11e7-a971-2b22e780ddfc	Error publishing AWS Health event to SNS { [InvalidParameter: Invalid parameter: Topic Name]
  message: 'Invalid parameter: Topic Name',
  code: 'InvalidParameter', 

Could this be the event Arn? please see the sample test that i ran below 

{
  "version": "0",
  "id": "7bf73129-1428-4cd3-a780-95db273d1602",
  "detail-type": "AWS Health Event",
  "source": "aws.health",
  "account": "123456789012",
  "time": "2016-06-05T06:27:57Z",
  "region": "us-east-1",
  "resources": [],
  "detail": {
    "eventArn": "arn:aws:sns:us-east-1:112888586165:AWS-Health/AWS_ELASTICLOADBALANCING_API_ISSUE_90353408594353980",
    "service": "ELASTICLOADBALANCING",
    "eventTypeCode": "AWS_ELASTICLOADBALANCING_API_ISSUE",
    "eventTypeCategory": "issue",
    "startTime": "Sat, 04 Jun 2016 05:01:10 GMT",
    "endTime": "Sat, 04 Jun 2016 05:30:57 GMT",
    "eventDescription": [
      {
        "language": "en_US",
        "latestDescription": "A description of the event will be provided here"
      }
    ]
  }
}

**Comment by premsurya** [comment]
Please make sure when you enter the SNS Topic Name it should be the topic name and not topic ARN ( It should be like "SNSTopic1" instead of ARN "arn:aws:sns:us-east-1:123456789012:SNSTopic1" )
