### ISSUE TITLE
Slack webhook url in committed code

### ISSUE THREAD

**Issue by 101shipit** [aws/aws-health-tools#25]
You might wanna remove this slack webhook url and cycle it https://github.com/aws/aws-health-tools/blob/master/slack-notifier/LambdaFunction.py#L31

**Comment by tipuq** [comment]
Thank you for raising this. It has been fixed: https://github.com/aws/aws-health-tools/tree/master/slack-notifier

**Comment by 101shipit** [comment]
👍 Hopefully you've cycled the webhook url in slack also as it's still in history.
