### ISSUE TITLE
Would this work if I set up in deferent region?

### ISSUE THREAD

**Issue by mineer22** [aws/aws-health-tools#27]
My test seems to say this does not work in other regions (other than us-east-1), is this true?

I have noted that AWS Health has a single endpoint... 
AWS Health has a single endpoint: health.us-east-1.amazonaws.com (HTTPS).
source - http://docs.aws.amazon.com/general/latest/gr/rande.html#awshealth_region

So I am right, or just doing a silly mistake when setting up in other regions?

**Comment by mwpatrick** [comment]
What kind of trouble are you seeing in your testing? 

You are correct that the Health API endpoint is in us-east-1 and that API is queried for all health event information. The health events have a region code in them allowing for the automation to target the proper region for action.

**Comment by tipuq** [comment]
Hi, just as mwpatrick mentioned, once you setup Amazon Cloudwatch events for AWS Health, the events will be created for the resource in the specific region that resource resides in. http://docs.aws.amazon.com/health/latest/ug/cloudwatch-events-health.html

**Comment by tipuq** [comment]
Closing, since the question was answered. Please open a new issue if anything else is needed.
