### ISSUE TITLE
Include addition resources from Sydney Summit demo

### ISSUE THREAD

**Issue by SamualBrown** [aws/aws-health-tools#39]
For the Sydney Summit demo of EBS_VOLUME_LOST, Steve Salim re-wrote most Lambdas into Python, and an Elasticsearch instance was included for visualisation.  An additional Stack was also created for the simulated "Important App".  The additional collateral created for this demo needs to be included in the EBS_VOLUME_LOST directory.

**Comment by tipuq** [comment]
Implemented and merged.
