### ISSUE TITLE
This tool needs support for Node.js v4.3 soon

### ISSUE THREAD

**Issue by ykmaloo** [aws/aws-health-tools#41]
Per the AWS Lambda runtime support policy , language runtimes that have been end-of-lifed by the supplier are deprecated in AWS Lambda. While invocations of Lambda functions configured to use Node.js v4.3 will continue to work normally, the ability to create new Lambda functions configured to use the Node.js v4.3 runtime will be disabled on July 31, 2018. Code updates to existing functions using Node.js v4.3 will be disabled on October 31, 2018.

**Comment by tipuq** [comment]
Thanks for raising this point. It's been tested and fixed in https://github.com/aws/aws-health-tools/commit/bcc2e28664085117eb8c40fb9f21c77696119f24
