### ISSUE TITLE
Lambda to slack fails to run due to line 13. 

### ISSUE THREAD

**Issue by kabads** [aws/aws-health-tools#42]
Lambda to slack- If you comment out line 13, the test will pass, although running the script locally doesn't have an error. I installed using the launch config and changed the URL to the region I am in, and then edited the Lambda script to include that region.

**Comment by tipuq** [comment]
Thanks Kabads, could you confirm if you are talking about the slack-notifier Lambda function?
https://github.com/aws/aws-health-tools/blob/master/slack-notifier/LambdaFunction.py

**Comment by tipuq** [comment]
Thanks for confirming. Line 13 of the Lambda function corresponds to https://github.com/aws/aws-health-tools/blob/master/slack-notifier/cfn-templates/slack-notifier.json#L92

message =  str(event['detail']['eventDescription'][0]['latestDescription'] + "\n\n<https://phd.aws.amazon.com/phd/home?region=us-east-1#/event-log?eventID=" + event['detail']['eventArn'] + "|Click here> for details.") 

I just tested this right now and the post to slack was successful. Could you explain how you are testing? If it's a sample event json, could you share that here? Thanks.

**Comment by tipuq** [comment]
Closing as the issue hasn't been reproed in a long time.
