### ISSUE TITLE
Minor issue when deploy SMS notifier stack

### ISSUE THREAD

**Issue by minuki** [aws/aws-health-tools#48]
When creating lambda function, rolled back with below error message. 
(Just changed the runtime parameter to nodejs8.10 and it works.)

The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 7b9da383-3405-11e9-af3d-bd3e517b9e46)

**Comment by tipuq** [comment]
Thank you for raising the issue. The version on S3 has been updated with the right nodejs runtime.
