### ISSUE TITLE
sns-topic-publisher in bucket uses older nodejs than the copy in git

### ISSUE THREAD

**Issue by bbacker** [aws/aws-health-tools#49]
sns-topic-publisher in bucket uses older nodejs than the copy in git

Hi - great examples! thank you.

I noticed when I visited https://github.com/aws/aws-health-tools/tree/master/sns-topic-publisher
and used the 'launch stack' button from the readme, it uses a copy from an s3 bucket
that produces a warning about nodejs4.3 being too old. However, the copy I see in this
repo uses nodejs 6.x so I suspect you need to copy the git version to the bucket again?

deploying by uploading
https://github.com/aws/aws-health-tools/blob/master/sns-topic-publisher/cfn-templates/sns-topic-publisher.yml
to cloudformation worked fine.

**Comment by tipuq** [comment]
Thank you very much for raising this issue. We have updated the files in S3.
