### ISSUE TITLE
Lookup_event updates the data on every 6 hours only

### ISSUE THREAD

**Issue by Aamir010** [aws/aws-health-tools#50]
Trying to pull the data on every 15 minutes but getting NULL events. But I can see the events on Cloud Trail console. If I alter the StartTime "datetime.datetime.now()-datetime.timedelta(hours=6)"
then it will polls the data. I can see thee pattern where I can get the updated events on every 6 hours.
Is it a known pattern ?

**Comment by tipuq** [comment]
Hi Aamir010, sorry for the delayed response here. Which AWS Health API call are you using (could you share an example) and are getting NULL events? Cloudtrail events are different from AWS Health events.

**Comment by tipuq** [comment]
Haven't gotten a response in 3 months, so closing.
