### ISSUE TITLE
Runtime update needed Nodejs 6.10 to 10.

### ISSUE THREAD

**Issue by ccharland** [aws/aws-health-tools#55]
New lambda functions can't be created with Runtime  "nodejs6.10", so this stack can't be used for testing unless the runtime version is changed.  

  Is there anything in the code to keep it from being changed to NodeJs 10?

**Comment by tipuq** [comment]
Tested the nodejs functions and they can be upgraded to 10.x without a problem, just need to update it.

**Comment by tipuq** [comment]
These have been updated, please raise a new issue if you see any issues.
