### ISSUE TITLE
Docuement Chatbot with Healt Tools

### ISSUE THREAD

**Issue by mbaitelman** [aws/aws-health-tools#59]
With the new [AWS Chabot (Beta)](https://aws.amazon.com/chatbot/) it is even simpler to get health alerts in Slack and Chime. 
Could this be added/instead of the existing Lambdas that handle this functionality?

**Comment by RobertDev** [comment]
AWS Chatbot supports receiving AWS Health notifications via CloudWatch Events.
This isn't a step-by-step document, but should get you started if you're still trying.
https://docs.aws.amazon.com/chatbot/latest/adminguide/related-services.html#cloudwatchevents

Just choose SNS as a target for your AWS Health CloudWatch Events Rule, then hook that SNS topic up to your AWS Chatbot and you should be good to go! :)
https://docs.aws.amazon.com/health/latest/ug/cloudwatch-events-health.html
