### ISSUE TITLE
SHD Notifier Chat Post error

### ISSUE THREAD

**Issue by gdougaws** [aws/aws-health-tools#66]
https://github.com/aws/aws-health-tools/blob/8cd98192fca269d70c23cc23cb8c38f57cef8808/shd-notifier/Health-Event-Chat-Post-LambdaFn.py#L84

After installing the SHD Notifier, the Cloudwatch logs showed the following error when it attempted to send a message to the configured Chime webhook:

`[ERROR] TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.`

The urllib documentation for v3.4+ (https://docs.python.org/3.4/library/urllib.request.html#urllib.request.Request) says that the data parameter "must be a bytes object", but the json.dumps function returns a string object.

Changing the statement to:

`req = Request(webhook, json.dumps(chat_message).encode('utf8'), header)`

Appears to correct the error.

**Comment by tipuq** [comment]
merged, thanks. 
https://github.com/aws/aws-health-tools/pull/67
