### ISSUE TITLE
SHD Notifier includes non-SHD issues

### ISSUE THREAD

**Issue by gdougaws** [aws/aws-health-tools#68]
https://github.com/aws/aws-health-tools/blob/b111b0fbbd537d1d74afb8cdd49142f2136881f2/shd-notifier/Health-Event-Poller-LambdaFn.py#L22

While all SHD events are of typeCategory issue, not all events of typeCategory issue are SHD events. This means that account specific issue events will also be reported by the SHD Notifier, when they do no appear on the SHD (only the PHD).

The eventScopeCode (https://docs.aws.amazon.com/health/latest/APIReference/API_Event.html#AWSHealth-Type-Event-eventScopeCode) should also be used to filter events available against an account, using the PUBLIC code, to ones that have been published on the Service Health Dashboard.

**Comment by tipuq** [comment]
https://github.com/aws/aws-health-tools/pull/69 was already merged, but please please re-open if anything else is pending.
