### ISSUE TITLE
How to do Test

### ISSUE THREAD

**Issue by rishi360** [aws/aws-health-tools#74]
Please let me know how to test when I use cloudformation.

**Comment by tipuq** [comment]
Hi Rishi, it depends on which automation you want to test and the type of test. You can add unit tests for Lambda functions, using invoke of the lambda function and verifying the outputs:
https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html

To test the actual Cloudformation templates you can use taskcat to implement a CI/CD Pipeline for AWS CloudFormation templates on AWS:
https://aws.amazon.com/quickstart/architecture/cicd-taskcat/

If you are looking to just manually test the one of the automations, you either run the Lambda function, create custom Cloudwatch events and rules or use the approach in https://github.com/aws/aws-health-tools/issues/63
