### ISSUE TITLE
  "errorMessage": "ERROR: Missing ENDPOINTARRAY Environment Variable for the Lambda Function!",

### ISSUE THREAD

**Issue by jormarcha** [aws/aws-health-tools#75]
What format should be the ARN ?
I have tried several options (SNS ARN exists) without success:

arn:aws:sns:us-east-1:xxxxxxxxxxxxxxxxxx:aws-health-NVirginia
arn:aws:sns:us-east-1:xxxxxxxxxxxxxxxxxx:aws-health-NVirginia]
["arn:aws:sns:us-east-1:xxxxxxxxxxxxxxxxxx:aws-health-NVirginia"]

**Comment by tipuq** [comment]
Hi Jormarcha, was this specific to https://github.com/aws/aws-health-tools/tree/master/sns-topic-publisher or some other utility?
SNS ARN should be the following format, but depending which cloudformation template you are using we can double check:
arn:aws:sns:us-east-1:123456789012:MyTopic

**Comment by jormarcha** [comment]
Hi tipuq, thans a lot for you help.
I try to launch again and comen back with news.
Maybe I’m working with the wrong template…

Thanks!!

**Comment by jormarcha** [comment]
Hello again tipuq, 
I have launched the sns-topic-publisher lambda but unfortunately the nodejs version is not supported:"Runtime update needed Nodejs 6.10 to 10." (https://github.com/aws/aws-health-tools/issues/55)

I see that the update could not be worked on yet.
Could you please let us know if you are planning this upgrade?

Thank you very much

**Comment by tipuq** [comment]
updated, please try now.
