### ISSUE TITLE
Slack Notifier setup python not supported

### ISSUE THREAD

**Issue by ofirshmuel** [aws/aws-health-tools#79]
Setup Slack Notifier using CloudFormation is not supporting python 3.9,
because the runtime parameter of Lambda use python 2.7 (out of support).

<img width="1125" alt="python2 7" src="https://user-images.githubusercontent.com/67951914/145183463-3a72210c-30ee-4c6f-ace7-9aa523498328.png">
.

**Comment by tipuq** [comment]
Hi, thanks for raising this. The S3 link in the README pointed towards the older CloudFormation template. It's been updated: https://github.com/aws/aws-health-tools/tree/master/slack-notifier
