### ISSUE TITLE
AWS_RISK_CREDENTIALS_EXPOSED uses python3.6

### ISSUE THREAD

**Issue by olekuz** [aws/aws-health-tools#84]
https://github.com/aws/aws-health-tools/tree/master/automated-actions/AWS_RISK_CREDENTIALS_EXPOSED uses python3.6 which is going to be deprecated, see https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by tipuq** [comment]
Updated to 3.8.
