### ISSUE TITLE
AWS Health Event Type for AWS_RISK_CREDENTIALS_EXPOSED Incorrect

### ISSUE THREAD

**Issue by rc-adammikolajczyk** [aws/aws-health-tools#93]
Hi, I recently deployed the AWS_RISK_CREDENTIALS_EXPOSED solution and found that the event type which is created does not match up to the event type being reported by AWS.

The event rule as automatically created:
```
{
  "detail-type": ["AWS Health Event"],
  "detail": {
    "eventTypeCode": ["AWS_RISK_CREDENTIALS_EXPOSED"],
    "service": ["RISK"],
    "eventTypeCategory": ["issue"]
  },
  "source": ["aws.health"]
}
```
However, the event as reported by AWS looks like this:
```
            "event": {
                "arn": "arn:aws:health:global::event/RISK/AWS_RISK_IAM_QUARANTINE/AWS_RISK_IAM_QUARANTI
NE-ovsY8KEPvK",
                "service": "RISK",
                "eventTypeCode": "AWS_RISK_IAM_QUARANTINE",
                "eventTypeCategory": "issue",
                "region": "global",
                "startTime": "2022-12-21T09:46:18.719000-05:00",
                "endTime": "2023-01-04T09:46:18.719000-05:00",
                "lastUpdatedTime": "2022-12-21T09:46:18.847000-05:00",
                "statusCode": "open",
                "eventScopeCode": "ACCOUNT_SPECIFIC"
            },
```
The "eventTypeCode" reported by AWS Health does not match the eventTypeCode which gets created. Not a huge problem to rectify, but if one didn't test this solution against real world leaked key events, you'd never know it and assume this was taking care of you, when it's not.

To match the eventTypeCode which AWS is reporting on, you'll need to add an EventBridge rule that looks like:
```
{
  "detail-type": ["AWS Health Event"],
  "detail": {
    "eventTypeCode": ["AWS_RISK_IAM_QUARANTINE"],
    "service": ["RISK"],
    "eventTypeCategory": ["issue"]
  },
  "source": ["aws.health"]
}
```

**Comment by Johnsonkdavid** [comment]
Hi @rc-adammikolajczyk  - You are correct. AWS is giving AWS_RISK_IAM_QUARANTINE instead of AWS_RISK_CREDENTIALS_EXPOSED.

**Comment by nnakai** [comment]
@rc-adammikolajczyk, @Johnsonkdavid thanks for your questions. AWS Health PM here. Actually, we use both EventTypes, and you can adapt this code sample to handle either one of them. There are slight differences between the two. AWS_RISK_IAM_QUARANTINE is used when the exposed key comes from an IAM user. The quarantine policy gets applied only to that specific user. AWS_RISK_CREDENTIALS_EXPOSED, however, is used when the root key is exposed. This causes the entire account to be restricted until you take action. So, it’s good to monitor for both of these EventTypes. Hope that answers your question. Feel free to let us know if anything else comes up.

**Comment by rc-adammikolajczyk** [comment]
Hi @nnakai thank you for that excellent explanation...I sincerely appreciate your taking the time - that was helpful and useful information.

Sincere Regards,
Adam
